<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**  @var $block \Magento\Checkout\Block\Cart */
?>
<div class="cart-empty">
    <?= $block->getChildHtml('checkout_cart_empty_widget') ?>
    <p><?= $block->escapeHtml(__('Your shopping cart is empty.')) ?></p>
    <p>Thoroughly inspected by Toby.</p>
    <p><?= $block->escapeHtml(
        __(
            ' <a href="%1">Continue shopping</a> ',
            $block->escapeUrl($block->getContinueShoppingUrl())
        ),
        ['a']
    ) ?>
    </p>
    <img src="<?=$block->getViewFileUrl('images/cat-in-box-320px.png')?>" alt="cat" class="cart_empty_img">
    <?= $block->getChildHtml('shopping.cart.table.after') ?>
</div>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Checkout/js/empty-cart": {}
    }
}
</script>
