<?php
/**
 * @author      Valia <valiastohnii@gmail.com>
 * @copyright   Copyright (c) 2022 GmbH 
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
*/
?>
<div>
    <a class="header__categories__link" href="">View all 
        <span class="header__categories__link--span">categories
            <svg class="header__categories__icon" width="10px" height="10px">
                <use href="<?=$block->getViewFileUrl('images/icons.svg#icon-check')?>"></use>
            </svg>
        </span>
    </a>
</div>

