<?php
/**
 * @author      Valia <valiastohnii@gmail.com>
 * @copyright   Copyright (c) 2022 GmbH 
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
*/
?>

<?php if (!$block->isContentMode() || $block->isMixedMode()) :?>
    <div class="category_content">
        <div class="category_section1">
            <div class="category_section1_list">
                <ul class="section1_list">
                    <li class="section1_item">
                        <a href="" class="section1_link">
                            <img src="<?=$block->getViewFileUrl('images/category/windows.png')?>" alt="" class="section1_link_img">
                            <p class="section1_link_title">Windows laptops</p>
                            <p class="section1_link_text">With the well-known Windows, you can use almost every application.</p>
                        </a>
                    </li>
                    <li class="section1_item">
                        <a href="" class="section1_link">
                            <img src="<?=$block->getViewFileUrl('images/category/apple.png')?>" alt="" class="section1_link_img">
                            <p class="section1_link_title">Apple MacBook</p>
                            <p class="section1_link_text">Use macOS and work together with other Apple devices.</p>
                        </a>
                    </li>
                    <li class="section1_item">
                        <a href="" class="section1_link">
                            <img src="<?=$block->getViewFileUrl('images/category/chrome.png')?>" alt="" class="section1_link_img">
                            <p class="section1_link_title">Back to School laptops</p>
                            <p class="section1_link_text">View all our promotions for student laptops here.</p>
                        </a>
                    </li>
                    <li class="section1_item">
                        <a href="" class="section1_link">
                            <img src="<?=$block->getViewFileUrl('images/category/acer.png')?>" alt="" class="section1_link_img">
                            <p class="section1_link_title">Business laptops</p>
                            <p class="section1_link_text">Windows Pro is safe and suitable for working remotely.</p>
                        </a>
                    </li>
                </ul>
            </div>
            <div class="category_section1_img">
                <a href="https://www.coolblue.nl/en/laptops/filter" class="section1_img_link">
                    <img src="<?=$block->getViewFileUrl('images/category/laptop.png')?>" alt="" class="section1_img_link_picture">
                </a>
            </div>
        </div>
        <div class="category_section2">
            <ul class="category_section2_list">
                    <li class="section2_item">
                        <a href="#" class="section2_link">
                            <svg class="section2_icon" width="16px" height="16px">
                                <use href="<?=$block->getViewFileUrl('images/icons.svg#icon-checkmark')?>"></use>
                            </svg>Ordered before <span class="section2_orange">23:59</span>, delivered tomorrow <span class="section2_orange"> for free</span></a>
                    </li>
                    <li class="section2_item">
                    <li class="section2_item">
                        <a href="https://www.coolblue.nl/en/customer-service/returns" class="section2_link">
                        <svg class="section2_icon" width="16px" height="16px">
                            <use href="<?=$block->getViewFileUrl('images/icons.svg#icon-checkmark')?>"></use>
                        </svg><span class="section2_orange">Free </span>exchange</a>
                    </li>
                    <li class="section2_item">
                        <a href="#" class="section2_link">
                        <svg class="section2_icon" width="16px" height="16px">
                            <use href="<?=$block->getViewFileUrl('images/icons.svg#icon-checkmark')?>"></use>
                        </svg><span class="section2_orange">Best </span>webshop 2021</a>
                    </li>
            </ul>
        </div>
        <div class="category_section3">
            <ul class="category_section3_list">
                <li class="section3_item">
                    <a href="" class="section3_link">
                        <img src="<?=$block->getViewFileUrl('images/category/hp-logo.png')?>" alt="" class="section3_link_img">
                    </a>
                </li>
                <li class="section3_item">
                    <a href="" class="section3_link">
                        <img src="<?=$block->getViewFileUrl('images/category/lenovo-logo.png')?>" alt="" class="section3_link_img">
                    </a>
                </li>
                <li class="section3_item">
                    <a href="" class="section3_link">
                        <img src="<?=$block->getViewFileUrl('images/category/acer-logo.png')?>" alt="" class="section3_link_img">
                    </a>
                </li>
                <li class="section3_item">
                    <a href="" class="section3_link">
                        <img src="<?=$block->getViewFileUrl('images/category/asus-logo.png')?>" alt="" class="section3_link_img">
                    </a>
                </li>
                <li class="section3_item">
                    <a href="" class="section3_link">
                        <img src="<?=$block->getViewFileUrl('images/category/samsung-logo.png')?>" alt="" class="section3_link_img section3_link_img--samsung">
                    </a>
                </li>
                <li class="section3_item">
                    <a href="" class="section3_link">
                        <img src="<?=$block->getViewFileUrl('images/category/msi-logo.png')?>" alt="" class="section3_link_img">
                    </a>
                </li>
            </ul>
        </div>
        <div class="category_section4">
            <h2 class="category_section4_title">Back to School laptops</h2>
            <ul class="category_section4_list">
                <li class="section4_item">
                    <a href="" class="section4_link">
                        <img src="<?=$block->getViewFileUrl('images/category/s4-1.png')?>" alt="" class="section4_link_img">
                        <p class="section4_link_title">All Back to School laptops</p>
                        <p class="section4_link_text">View all student laptops from our assortment here.</p>
                    </a>                       
                </li>
                <li class="section4_item">
                    <a href="" class="section4_link">
                        <img src="<?=$block->getViewFileUrl('images/category/s4-2.png')?>" alt="" class="section4_link_img">
                        <p class="section4_link_title">Laptops for social, cultural, and economics studies</p>
                        <p class="section4_link_text">These laptops are ideal for working on reports and presentations.</p>
                    </a> 
                </li>
                <li class="section4_item">
                    <a href="" class="section4_link">
                        <img src="<?=$block->getViewFileUrl('images/category/s4-3.png')?>" alt="" class="section4_link_img">
                        <p class="section4_link_title">Laptops for creative studies</p>
                        <p class="section4_link_text">These fast laptops are ideal for photo and video editing.</p>
                    </a> 
                </li>
                <li class="section4_item">
                    <a href="" class="section4_link">
                        <img src="<?=$block->getViewFileUrl('images/category/s4-4.png')?>" alt="" class="section4_link_img">
                        <p class="section4_link_title">Laptops for technical studies</p>
                        <p class="section4_link_text">Create 3D designs on these laptops with powerful video cards.</p>
                    </a>
                </li>
            </ul>
        </div>
        <div class="category_section5">
            <h2 class="category_section5_title">Laptops</h2>
            <div class="category_section5_blocks">
                <img class="category_section5_img" src="<?=$block->getViewFileUrl('images/category/s5-1.png')?>" alt="customer">
                <div class="category_section5_item">
                    <a href="" class="section5_link">
                        <img src="<?=$block->getViewFileUrl('images/category/s5-2.png')?>" alt="" class="section5_link_img">
                        <p class="section5_link_title">All laptops</p>
                        <p class="section5_link_text">Want to buy a new laptop? View our large assortment of laptops and find the laptop that suits your use.</p>
                    </a> 
                </div>
                <div class="category_section5_block">
                    <div class="section5_block_description">
                    <p class="section5_block_title">Help choosing</p>
                    <p class="section5_block_text">Answer some questions and find the best one for you.</p>
                    </div>
                    <img src="<?=$block->getViewFileUrl('images/category/s5-3.png')?>" alt="" class="section5_block_img">
                    <button class="section5_block_button">Start the product filter</button>
                </div>
            </div>
        </div>
        <div class="category_section6">
            <h2 class="category_section6_title">Quickly navigate to</h2>
            <ul class="category_section6_list">
                <li class="section6_item"><a class="section6_link" href="">Coolblue's Choice laptops</a></li>
                <li class="section6_item"><a class="section6_link" href="">Windows 10 student laptops</a></li>
                <li class="section6_item"><a class="section6_link" href="">Gaming laptops</a></li>
                <li class="section6_item"><a class="section6_link" href="">2-in-1 laptops</a></li>
                <li class="section6_item"><a class="section6_link" href="">Windows laptops with Microsoft Office</a></li>
                <li class="section6_item"><a class="section6_link" href="">Laptops for photo editing</a></li>
            </ul>
        </div>
        <div class="category_section2">
            <ul class="category_section2_list">
                    <li class="section2_item">
                        <a href="#" class="section2_link">
                            <svg class="section2_icon" width="16px" height="16px">
                                <use href="<?=$block->getViewFileUrl('images/icons.svg#icon-checkmark')?>"></use>
                            </svg>Ordered before <span class="section2_orange">23:59</span>, delivered tomorrow <span class="section2_orange"> for free</span></a>
                    </li>
                    <li class="section2_item">
                    <li class="section2_item">
                        <a href="https://www.coolblue.nl/en/customer-service/returns" class="section2_link">
                        <svg class="section2_icon" width="16px" height="16px">
                            <use href="<?=$block->getViewFileUrl('images/icons.svg#icon-checkmark')?>"></use>
                        </svg><span class="section2_orange">Free </span>exchange</a>
                    </li>
                    <li class="section2_item">
                        <a href="#" class="section2_link">
                        <svg class="section2_icon" width="16px" height="16px">
                            <use href="<?=$block->getViewFileUrl('images/icons.svg#icon-checkmark')?>"></use>
                        </svg><span class="section2_orange">Best </span>webshop 2021</a>
                    </li>
            </ul>
        </div>
        <div class="category_section7">
            <h2 class="category_section7_title">Inspiration</h2>
            <ul class="category_section7_list">
                <li class="section7_item"><a class="section7_link" href="">Study with HP</a></li>
                <li class="section7_item"><a class="section7_link" href="">Home</a></li>
                <li class="section7_item"><a class="section7_link" href="">Gaming</a></li>
                <li class="section7_item"><a class="section7_link" href="">On its way</a></li>
                <li class="section7_item"><a class="section7_link" href="">Graphic tasks</a></li>
                <li class="section7_item"><a class="section7_link" href="">Office</a></li>
            </ul>
            <div>
                <?php
                echo $this->getLayout()
                ->createBlock('Magento\Cms\Block\Block')
                ->setBlockId('inspiration')
                ->toHtml();
                ?>
            </div>
        </div>
        <div class="category_section8">
            <h2 class="category_section8_title">Advice</h2>
            <ul class="category_section8_list">
                <li class="section8_item">
                    <img src="<?=$block->getViewFileUrl('images/category/s8-1.png')?>" alt="" class="section8_img">
                    <p class="section8_title">Which laptop suits you?</p>
                    <p class="section8_text">Everybody uses a laptop once in a while. There are many different types of laptops. We divide them into 3 types, Windows laptops, Apple MacBook, and Google Chromebook. They differ in appearance and name, but also in operating system. Which laptop you need depends on both preference and use. There are students who use it at school, employees who use a laptop for business, and families who need a laptop for home use. Aren't you sure yet which laptop you want to buy? Get advice from our laptop expert and be inspired.</p>
                    <a class="section8_link" href="">> Read the advice on which laptop is suitable for you here</a>
                </li>
                <li class="section8_item">
                    <img src="<?=$block->getViewFileUrl('images/category/s8-2.png')?>" alt="" class="section8_img">
                    <p class="section8_title">Which laptop size suits you?</p>
                    <p class="section8_text">The size of a laptop depends on the use. If you use it on the go for work or school, it's useful that the laptop is up to 14 inches and compact and doesn't weigh more than 1.5kg. That way, you can easily take the laptop with you in your laptop bag or backpack. A larger size laptop is mainly useful when you game a lot or edit photos or videos. So, think of what you want to use the laptop for beforehand. Do you want more information? We're happy to help you with some examples.</p>
                    <a class="section8_link" href="">> Read the advice on choosing an inch-size here</a>
                </li>
                <li class="section8_item">
                    <img src="<?=$block->getViewFileUrl('images/category/s8-3.png')?>" alt="" class="section8_img">
                    <p class="section8_title">What's Windows 11?</p>
                    <p class="section8_text">Windows 11 is the latest operating system by Microsoft. More and more new laptops have this new version by default. Windows 11 looks modern and calm at the same time, thanks to the transparent windows. Even though there are innovations, this version doesn't feel different. You don't have to worry about getting used to it when you switch. If you currently have a laptop with Windows 10, there's a great chance that you can upgrade it to Windows 11 for free. We're happy to explain to you how you know the upgrade is ready for you.</p>
                    <a class="section8_link" href="">> Read everything on Windows 11 here</a>
                </li>
            </ul>
        </div>
        <div class="category_section9">
            <h2 class="category_section9_title">Laptops for every usage situation</h2>
            <ul class="category_section9_list">
                <li class="section9_item">
                    <a class="section9_link" href="">
                        <img class="section9_img" src="<?=$block->getViewFileUrl('images/category/s4-3.png')?>" alt="">
                        <p class="section9_title">Laptops for school and studies</p>
                    </a>                       
                </li>
                <li class="section9_item">
                    <a class="section9_link" href="">
                        <img class="section9_img" src="<?=$block->getViewFileUrl('images/category/s4-3.png')?>" alt="">
                        <p class="section9_title">Gaming laptops</p>
                    </a> 
                </li>
                <li class="section9_item">
                    <a class="section9_link" href="">
                        <img class="section9_img" src="<?=$block->getViewFileUrl('images/category/s4-3.png')?>" alt="">
                        <p class="section9_title">Laptops for photo editing</p>
                    </a> 
                </li>
                <li class="section9_item">
                    <a class="section9_link" href="">
                        <img class="section9_img" src="<?=$block->getViewFileUrl('images/category/s4-3.png')?>" alt="">
                        <p class="section9_title">Laptops for video editing</p>
                    </a>
                </li>
                <li class="section9_item">
                    <a class="section9_link" href="">
                        <img class="section9_img" src="<?=$block->getViewFileUrl('images/category/s4-3.png')?>" alt="">
                        <p class="section9_title">Laptops for on the go</p>
                    </a>
                </li>
            </ul>
        </div>
        <div class="category_section10">
            <h2 class="category_section9_title">Laptops in the store</h2>
            <ul class="category_section8_list">
                <li class="section8_item">
                    <img class="section8_img" src="<?=$block->getViewFileUrl('images/category/s8-1.png')?>" alt="">
                    <p class="section8_title">Find a store near you</p>
                    <p class="section8_text">You can choose a laptop based on the hardware specifications. But it's also nice to know how sturdy the hinges are or how heavy that 17-inch laptop actually is. There's always a large stock of laptops in our stores.</p>
                    <button class="section10_button">Visit one of our stores</button>                  
                </li>
                <li class="section8_item">
                    <img class="section8_img" src="<?=$block->getViewFileUrl('images/category/s5-1.png')?>" alt="">
                    <p class="section8_title">Advice by appointment</p>
                    <p class="section8_text">Do you want 8GB RAM? Or do you need 32GB? Do you keep everything in the cloud or do you need internal storage? And what's the difference between M1 and M2? Make an appointment with one of our experts in our stores and they'll answer all your questions.</p>
                    <button class="section10_button">Make an appointment</button>
                </li>
                <li class="section8_item">
                    <img class="section8_img" src="<?=$block->getViewFileUrl('images/category/s8-3.png')?>" alt="">
                    <p class="section8_title">Which laptops can you find in our stores?</p>
                    <p class="section8_text">There are many laptops to view in our stores. Do you want to know if the laptop of your choice is available in our store in your area? View the page below and select the desired location. The coffee is already waiting for you.</p>
                    <button class="section10_button">View these laptops in the store</button>
                </li>
            </ul>
        </div>
        <div class="category_section11">
            <ul class="category_section11_lists">
                <li class="category_section11_item">
                    <h3 class="category_section11_item_title">A</h3>
                    <ul class="category_section11_item_list">
                        <li><a class="category_section11_item_link" href="">Acer laptops</a></li>
                        <li><a class="category_section11_item_link" href="">Apple MacBook</a></li>
                        <li><a class="category_section11_item_link" href="">Asus laptops</a></li>
                    </ul>
                </li>
                <li class="category_section11_item">
                    <h3 class="category_section11_item_title">B</h3>
                    <ul class="category_section11_item_list">
                        <li><a class="category_section11_item_link" href="">Back to School laptops</a></li>
                        <li><a class="category_section11_item_link" href="">Best laptops according to our customers</a></li>
                        <li><a class="category_section11_item_link" href="">Black Friday laptop deals</a></li>
                    </ul>
                </li>
                <li class="category_section11_item">
                    <h3 class="category_section11_item_title">C</h3>
                    <ul class="category_section11_item_list">
                        <li><a class="category_section11_item_link" href="">Cheap laptops</a></li>
                        <li><a class="category_section11_item_link" href="">Christmas laptop deals</a></li>
                        <li><a class="category_section11_item_link" href="">Chromebooks</a></li>
                    </ul>
                </li>
                <li class="category_section11_item">
                    <h3 class="category_section11_item_title">D</h3>
                    <ul class="category_section11_item_list">
                        <li><a class="category_section11_item_link" href="">Dell laptops</a></li>
                        <li><a class="category_section11_item_link" href="">Dynabook laptops</a></li>
                        <li><a class="category_section11_item_link" href="">Dynabook laptops</a></li>
                    </ul>
                </li>
            </ul>
        </div>
        <div class="category_section12">
            <hr class="category_section12_hr"> 
            <?php
                echo $this->getLayout()
                ->createBlock('Magento\Cms\Block\Block')
                ->setBlockId('Previously_viewed')
                ->toHtml();
            ?>
        </div>
    </div>
<?php endif; ?>