<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */
?>
<?php if (!$block->isContentMode() || $block->isMixedMode()) :?>
    <!-- <?= $block->getProductListHtml() ?> -->
    <div class="category_content">
        <div class="category_section1">
            <div class="category_section1_list">
                <ul class="section1_list">
                    <li class="section1_item">
                        <a href="" class="section1_link">
                            <img src="<?=$block->getViewFileUrl('images/category/windows.png')?>" alt="" class="section1_link_img">
                            <p class="section1_link_title">Windows laptops</p>
                            <p class="section1_link_text">With the well-known Windows, you can use almost every application.</p>
                        </a>
                    </li>
                    <li class="section1_item">
                        <a href="" class="section1_link">
                            <img src="<?=$block->getViewFileUrl('images/category/apple.png')?>" alt="" class="section1_link_img">
                            <p class="section1_link_title">Apple MacBook</p>
                            <p class="section1_link_text">Use macOS and work together with other Apple devices.</p>
                        </a>
                    </li>
                    <li class="section1_item">
                        <a href="" class="section1_link">
                            <img src="<?=$block->getViewFileUrl('images/category/chrome.png')?>" alt="" class="section1_link_img">
                            <p class="section1_link_title">Back to School laptops</p>
                            <p class="section1_link_text">View all our promotions for student laptops here.</p>
                        </a>
                    </li>
                    <li class="section1_item">
                        <a href="" class="section1_link">
                            <img src="<?=$block->getViewFileUrl('images/category/acer.png')?>" alt="" class="section1_link_img">
                            <p class="section1_link_title">Business laptops</p>
                            <p class="section1_link_text">Windows Pro is safe and suitable for working remotely.</p>
                        </a>
                    </li>
                </ul>
            </div>
            <div class="category_section1_img">
                <a href="https://www.coolblue.nl/en/laptops/filter" class="section1_img_link">
                    <img src="<?=$block->getViewFileUrl('images/category/laptop.png')?>" alt="" class="section1_img_link_picture">
                </a>
            </div>
        </div>
        <div class="category_section2">
            <ul class="category_section2_list">
                    <li class="section2_item">
                        <a href="#" class="section2_link">
                            <svg class="section2_icon" width="16px" height="16px">
                                <use href="<?=$block->getViewFileUrl('images/icons.svg#icon-checkmark')?>"></use>
                            </svg>Ordered before <span class="section2_orange">23:59</span>, delivered tomorrow <span class="section2_orange"> for free</span></a>
                    </li>
                    <li class="section2_item">
                    <li class="section2_item">
                        <a href="https://www.coolblue.nl/en/customer-service/returns" class="section2_link">
                        <svg class="section2_icon" width="16px" height="16px">
                            <use href="<?=$block->getViewFileUrl('images/icons.svg#icon-checkmark')?>"></use>
                        </svg><span class="section2_orange">Free </span>exchange</a>
                    </li>
                    <li class="section2_item">
                        <a href="#" class="section2_link">
                        <svg class="section2_icon" width="16px" height="16px">
                            <use href="<?=$block->getViewFileUrl('images/icons.svg#icon-checkmark')?>"></use>
                        </svg><span class="section2_orange">Best </span>webshop 2021</a>
                    </li>
            </ul>
        </div>
        <div class="category_section3">
            <ul class="category_section3_list">
                <li class="section3_item">
                    <a href="" class="section3_link">
                        <img src="<?=$block->getViewFileUrl('images/category/hp-logo.png')?>" alt="" class="section3_link_img">
                    </a>
                </li>
                <li class="section3_item">
                    <a href="" class="section3_link">
                        <img src="<?=$block->getViewFileUrl('images/category/lenovo-logo.png')?>" alt="" class="section3_link_img">
                    </a>
                </li>
                <li class="section3_item">
                    <a href="" class="section3_link">
                        <img src="<?=$block->getViewFileUrl('images/category/acer-logo.png')?>" alt="" class="section3_link_img">
                    </a>
                </li>
                <li class="section3_item">
                    <a href="" class="section3_link">
                        <img src="<?=$block->getViewFileUrl('images/category/asus-logo.png')?>" alt="" class="section3_link_img">
                    </a>
                </li>
                <li class="section3_item">
                    <a href="" class="section3_link">
                        <img src="<?=$block->getViewFileUrl('images/category/samsung-logo.png')?>" alt="" class="section3_link_img section3_link_img--samsung">
                    </a>
                </li>
                <li class="section3_item">
                    <a href="" class="section3_link">
                        <img src="<?=$block->getViewFileUrl('images/category/msi-logo.png')?>" alt="" class="section3_link_img">
                    </a>
                </li>
            </ul>
        </div>
        <div class="category_section4">
            <h2 class="category_section4_title">Back to School laptops</h2>
            <ul class="category_section4_list">
                <li class="section4_item">
                    <a href="" class="section4_link">
                        <img src="<?=$block->getViewFileUrl('images/category/s4-1.png')?>" alt="" class="section4_link_img">
                        <p class="section4_link_title">All Back to School laptops</p>
                        <p class="section4_link_text">View all student laptops from our assortment here.</p>
                    </a>                       
                </li>
                <li class="section4_item">
                    <a href="" class="section4_link">
                        <img src="<?=$block->getViewFileUrl('images/category/s4-2.png')?>" alt="" class="section4_link_img">
                        <p class="section4_link_title">Laptops for social, cultural, and economics studies</p>
                        <p class="section4_link_text">These laptops are ideal for working on reports and presentations.</p>
                    </a> 
                </li>
                <li class="section4_item">
                    <a href="" class="section4_link">
                        <img src="<?=$block->getViewFileUrl('images/category/s4-3.png')?>" alt="" class="section4_link_img">
                        <p class="section4_link_title">Laptops for creative studies</p>
                        <p class="section4_link_text">These fast laptops are ideal for photo and video editing.</p>
                    </a> 
                </li>
                <li class="section4_item">
                    <a href="" class="section4_link">
                        <img src="<?=$block->getViewFileUrl('images/category/s4-4.png')?>" alt="" class="section4_link_img">
                        <p class="section4_link_title">Laptops for technical studies</p>
                        <p class="section4_link_text">Create 3D designs on these laptops with powerful video cards.</p>
                    </a>
                </li>
            </ul>
        </div>
        <div class="category_section5">
            <h2 class="category_section5_title">Laptops</h2>
            <div class="category_section5_blocks">
                <img class="category_section5_img" src="<?=$block->getViewFileUrl('images/category/s5-1.png')?>" alt="customer">
                <div class="category_section5_item">
                    <a href="" class="section5_link">
                        <img src="<?=$block->getViewFileUrl('images/category/s5-2.png')?>" alt="" class="section5_link_img">
                        <p class="section5_link_title">All laptops</p>
                        <p class="section5_link_text">Want to buy a new laptop? View our large assortment of laptops and find the laptop that suits your use.</p>
                    </a> 
                </div>
                <div class="category_section5_block">
                    <div class="section5_block_description">
                    <p class="section5_block_title">Help choosing</p>
                    <p class="section5_block_text">Answer some questions and find the best one for you.</p>
                    </div>
                    <img src="<?=$block->getViewFileUrl('images/category/s5-3.png')?>" alt="" class="section5_block_img">
                    <button class="section5_block_button">Start the product filter</button>
                </div>
            </div>
        </div>
        <div class="category_section6">
            <h2 class="category_section6_title">Quickly navigate to</h2>
            <ul class="category_section6_list">
                <li class="section6_item"><a class="section6_link" href="">Coolblue's Choice laptops</a></li>
                <li class="section6_item"><a class="section6_link" href="">Windows 10 student laptops</a></li>
                <li class="section6_item"><a class="section6_link" href="">Gaming laptops</a></li>
                <li class="section6_item"><a class="section6_link" href="">2-in-1 laptops</a></li>
                <li class="section6_item"><a class="section6_link" href="">Windows laptops with Microsoft Office</a></li>
                <li class="section6_item"><a class="section6_link" href="">Laptops for photo editing</a></li>
            </ul>
        </div>
        <div class="category_section2">
            <ul class="category_section2_list">
                    <li class="section2_item">
                        <a href="#" class="section2_link">
                            <svg class="section2_icon" width="16px" height="16px">
                                <use href="<?=$block->getViewFileUrl('images/icons.svg#icon-checkmark')?>"></use>
                            </svg>Ordered before <span class="section2_orange">23:59</span>, delivered tomorrow <span class="section2_orange"> for free</span></a>
                    </li>
                    <li class="section2_item">
                    <li class="section2_item">
                        <a href="https://www.coolblue.nl/en/customer-service/returns" class="section2_link">
                        <svg class="section2_icon" width="16px" height="16px">
                            <use href="<?=$block->getViewFileUrl('images/icons.svg#icon-checkmark')?>"></use>
                        </svg><span class="section2_orange">Free </span>exchange</a>
                    </li>
                    <li class="section2_item">
                        <a href="#" class="section2_link">
                        <svg class="section2_icon" width="16px" height="16px">
                            <use href="<?=$block->getViewFileUrl('images/icons.svg#icon-checkmark')?>"></use>
                        </svg><span class="section2_orange">Best </span>webshop 2021</a>
                    </li>
            </ul>
        </div>
        <div>
            <h2>Inspiration</h2>
            <ul>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
            </ul>
            <img src="" alt="">
        </div>
        <div>
            <h2>Advice</h2>
            <ul>
                <li></li>
                <li></li>
                <li></li>
            </ul>
        </div>
        <div>
            <h2>Laptops for every usage situation</h2>
            <ul>
                <li>
                    <a href="">
                        <img src="" alt="">
                        <p>Laptops for school and studies</p>
                    </a>                       
                </li>
                <li>
                    <a href="">
                        <img src="" alt="">
                        <p>Gaming laptops</p>
                    </a> 
                </li>
                <li>
                    <a href="">
                        <img src="" alt="">
                        <p>Laptops for photo editing</p>
                    </a> 
                </li>
                <li>
                    <a href="">
                        <img src="" alt="">
                        <p>Laptops for video editing</p>
                    </a>
                </li>
                <li>
                    <a href="">
                        <img src="" alt="">
                        <p>Laptops for on the go</p>
                    </a>
                </li>
            </ul>
        </div>
        <div>
            <h2>Laptops in the store</h2>
            <ul>
                <li>
                    
                        <img src="" alt="">
                        <p>Find a store near you</p>
                        <p>You can choose a laptop based on the hardware specifications. But it's also nice to know how sturdy the hinges are or how heavy that 17-inch laptop actually is. There's always a large stock of laptops in our stores.</p>
                        <button>Visit one of our stores</button>
                                          
                </li>
                <li>
                   
                        <img src="" alt="">
                        <p>Advice by appointment</p>
                        <p>Do you want 8GB RAM? Or do you need 32GB? Do you keep everything in the cloud or do you need internal storage? And what's the difference between M1 and M2? Make an appointment with one of our experts in our stores and they'll answer all your questions.</p>
                        <button>Make an appointment</button>
                    
                </li>
                <li>
                    
                        <img src="" alt="">
                        <p>Which laptops can you find in our stores?</p>
                        <p>There are many laptops to view in our stores. Do you want to know if the laptop of your choice is available in our store in your area? View the page below and select the desired location. The coffee is already waiting for you.</p>
                        <button>View these laptops in the store</button>
                   
                </li>
            </ul>
        </div>
        <div>
            <ul>
                <li><ul></ul></li>
                <li><ul></ul></li>
                <li><ul></ul></li>
                <li><ul></ul></li>
            </ul>
        </div>
    </div>
<?php endif; ?>
