<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block \Magento\Catalog\Block\Product\AbstractProduct */ ?>
<?= $block->getReviewsSummaryHtml($block->getProduct(), false, true) ?>
<div class="product_main_rewiew">
    <p class="product_main_rewiew_title">In the version</p>
    <input type="text">
    <p class="product_main_rewiew_title">Purchase your Word and Excel here Explanation</p>
    <div class="product_main_rewiew_box">
        <img src="<?=$block->getViewFileUrl('images/1641823.png')?>" alt="" class="product_main_rewiew_img">
        <div>
            <p>Office 365 Personal NL Subscription 1 year</p>
            <a href="">Select alternative</a>
        </div>
        <p class="product_main_rewiew_price">69,90</p>
    </div>
</div>
