<?php
/**
 * @author      Valia <valiastohnii@gmail.com>
 * @copyright   Copyright (c) 2022 GmbH 
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
*/

/* @var \Magento\Wishlist\Block\Link $block */
?>
<li class="link wishlist" data-bind="scope: 'wishlist'">
    <a <?= /* @noEscape */ $block->getLinkAttributes() ?>>
    <!-- <?= $block->escapeHtml($block->getLabel()) ?> -->
        <!-- ko if: wishlist().counter -->
        <!-- <span data-bind="text: wishlist().counter" class="counter qty"></span> -->
        <!-- /ko -->
        <svg class="wishlist__link__icon" width="24px" height="24px">
            <use href="<?=$block->getViewFileUrl('images/icons.svg#icon-heart')?>"></use>
        </svg>
    </a>
</li>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "wishlist": {
                        "component": "Magento_Wishlist/js/view/wishlist"
                    }
                }
            }
        }
    }

</script>
