<?php
/**
 * @author      Valia <valiastohnii@gmail.com>
 * @copyright   Copyright (c) 2022 GmbH 
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
*/
?>

<div class="laptopswidget_content">
    <p class="laptopswidget_description">With a Windows laptop, Chromebook, MacBook, Windows desktop, or iMac from Coolblue, you can browse the internet, game to your heart's content, and type out reports in Word. Our monitors display all images smoothly in Full HD or even 4K resolution. You easily connect laptops to your monitor via a docking station. Don't feel like purchasing a separate monitor? Choose an all-in-one PC that combines a desktop and a screen. You can transport your laptop damage-free in a laptop cover. If you want to work comfortably, choose a keyboard and mouse.</p>
    <ul class="laptopswidget_lists">
        <li class="laptopswidget_item">
            <h2 class="laptopswidget_item_title">Laptops</h2>
            <ul class="laptopswidget_item_list">
                <li class="list_item">
                    <a class="list_link" href="http://cool-blue.ddev.site/index.php/what-is-new/valia.html">
                        <img class="list_img" src="<?=$block->getViewFileUrl('CoolBlueModule_Module::images/category/l1-1.png')?>" alt="">
                        <p class="list_title">Laptops</p>
                    </a>
                </li>
                <li class="list_item">
                    <a class="list_link" href="">
                        <img class="list_img" src="<?=$block->getViewFileUrl('CoolBlueModule_Module::images/category/l1-2.png')?>" alt="">
                        <p class="list_title">Gaming laptops</p>
                    </a>
                </li>
                <li class="list_item">
                    <a class="list_link" href="">
                        <img class="list_img" src="<?=$block->getViewFileUrl('CoolBlueModule_Module::images/category/l1-3.png')?>" alt="">
                        <p class="list_title">Chromebook models</p>
                    </a>
                </li>
                <li class="list_item">
                    <a class="list_link" href="">
                        <img class="list_img" src="<?=$block->getViewFileUrl('CoolBlueModule_Module::images/category/l1-2.png')?>" alt="">
                        <p class="list_title">Business laptops</p>
                    </a>
                </li>
                <li class="list_item">
                    <a class="list_link" href="">
                        <img class="list_img" src="<?=$block->getViewFileUrl('CoolBlueModule_Module::images/category/l1-3.png')?>" alt="">
                        <p class="list_title">Apple MacBook</p>
                    </a>
                </li>
                <li class="list_item">
                    <a class="list_link" href="">
                        <img class="list_img" src="<?=$block->getViewFileUrl('CoolBlueModule_Module::images/category/l1-1.png')?>" alt="">
                        <p class="list_title">Advice on laptops</p>
                    </a>
                </li>
            </ul>
        </li>
        <li class="laptopswidget_item">
            <h2 class="laptopswidget_item_title">Desktops</h2>
            <ul class="laptopswidget_item_list">
                <li class="list_item">
                    <a class="list_link" href="">
                        <img class="list_img" src="<?=$block->getViewFileUrl('CoolBlueModule_Module::images/category/l2-1.png')?>" alt="">
                        <p class="list_title">Desktops</p>
                    </a>
                </li>
                <li class="list_item">
                    <a class="list_link" href="">
                        <img class="list_img" src="<?=$block->getViewFileUrl('CoolBlueModule_Module::images/category/l2-2.png')?>" alt="">
                        <p class="list_title">Gaming PCs</p>
                    </a>
                </li>
                <li class="list_item">
                    <a class="list_link" href="">
                        <img class="list_img" src="<?=$block->getViewFileUrl('CoolBlueModule_Module::images/category/l2-3.png')?>" alt="">
                        <p class="list_title">All-in-one PCs</p>
                    </a>
                </li>
                <li class="list_item">
                    <a class="list_link" href="">
                        <img class="list_img" src="<?=$block->getViewFileUrl('CoolBlueModule_Module::images/category/l2-1.png')?>" alt="">
                        <p class="list_title">Business PCs</p>
                    </a>
                </li>
                <li class="list_item">
                    <a class="list_link" href="">
                        <img class="list_img" src="<?=$block->getViewFileUrl('CoolBlueModule_Module::images/category/l2-3.png')?>" alt="">
                        <p class="list_title">Apple Mac</p>
                    </a>
                </li>
                <li class="list_item">
                    <a class="list_link" href="">
                        <img class="list_img" src="<?=$block->getViewFileUrl('CoolBlueModule_Module::images/category/l2-6.png')?>" alt="">
                        <p class="list_title">Advice on desktops</p>
                    </a>
                </li>
            </ul>
        </li>
        <li class="laptopswidget_item">
            <h2 class="laptopswidget_item_title">Monitors</h2>
            <ul class="laptopswidget_item_list">
                <li class="list_item">
                    <a class="list_link" href="">
                        <img class="list_img" src="<?=$block->getViewFileUrl('CoolBlueModule_Module::images/category/l3-1.png')?>" alt="">
                        <p class="list_title">Monitors</p>
                    </a>
                </li>
                <li class="list_item">
                    <a class="list_link" href="">
                        <img class="list_img" src="<?=$block->getViewFileUrl('CoolBlueModule_Module::images/category/l3-2.png')?>" alt="">
                        <p class="list_title">Gaming monitors</p>
                    </a>
                </li>
                <li class="list_item">
                    <a class="list_link" href="">
                        <img class="list_img" src="<?=$block->getViewFileUrl('CoolBlueModule_Module::images/category/l3-3.png')?>" alt="">
                        <p class="list_title">Ultrawide monitors</p>
                    </a>
                </li>
                <li class="list_item">
                    <a class="list_link" href="">
                        <img class="list_img" src="<?=$block->getViewFileUrl('CoolBlueModule_Module::images/category/l3-1.png')?>" alt="">
                        <p class="list_title">Business monitors</p>
                    </a>
                </li>
                <li class="list_item">
                    <a class="list_link" href="">
                        <img class="list_img" src="<?=$block->getViewFileUrl('CoolBlueModule_Module::images/category/l3-2.png')?>" alt="">
                        <p class="list_title">Monitor bundles</p>
                    </a>
                </li>
                <li class="list_item">
                    <a class="list_link" href="">
                        <img class="list_img" src="<?=$block->getViewFileUrl('CoolBlueModule_Module::images/category/l3-6.png')?>" alt="">
                        <p class="list_title">Advice on monitors</p>
                    </a>
                </li>
            </ul>
        </li>
        <li class="laptopswidget_item">
            <h2 class="laptopswidget_item_title">Popular accessories</h2>
            <ul class="laptopswidget_item_list laptopswidget_item_list--popular">
                <li class="list_item">
                    <a class="list_link" href="">
                        <img class="list_img" src="<?=$block->getViewFileUrl('CoolBlueModule_Module::images/category/l4-1.png')?>" alt="">
                        <p class="list_title">Mouses</p>
                    </a>
                </li>
                <li class="list_item">
                    <a class="list_link" href="">
                        <img class="list_img" src="<?=$block->getViewFileUrl('CoolBlueModule_Module::images/category/l4-2.png')?>" alt="">
                        <p class="list_title">Office software</p>
                    </a>
                </li>
                <li class="list_item">
                    <a class="list_link" href="">
                        <img class="list_img" src="<?=$block->getViewFileUrl('CoolBlueModule_Module::images/category/l4-3.png')?>" alt="">
                        <p class="list_title">Laptop covers</p>
                    </a>
                </li>
                <li class="list_item">
                    <a class="list_link" href="">
                        <img class="list_img" src="<?=$block->getViewFileUrl('CoolBlueModule_Module::images/category/l4-4.png')?>" alt="">
                        <p class="list_title">Keyboards</p>
                    </a>
                </li>
                <li class="list_item">
                    <a class="list_link" href="">
                        <img class="list_img" src="<?=$block->getViewFileUrl('CoolBlueModule_Module::images/category/l4-2.png')?>" alt="">
                        <p class="list_title">Keyboard and mouse sets</p>
                    </a>
                </li>
                <li class="list_item">
                    <a class="list_link" href="">
                        <img class="list_img" src="<?=$block->getViewFileUrl('CoolBlueModule_Module::images/category/l4-6.png')?>" alt="">
                        <p class="list_title">Docking stations</p>
                    </a>
                </li>
                <li class="list_item">
                    <a class="list_link" href="">
                        <img class="list_img" src="<?=$block->getViewFileUrl('CoolBlueModule_Module::images/category/l4-7.png')?>" alt="">
                        <p class="list_title">Acer</p>
                    </a>
                </li>
                <li class="list_item">
                    <a class="list_link" href="">
                        <img class="list_img" src="<?=$block->getViewFileUrl('CoolBlueModule_Module::images/category/l4-8.png')?>" alt="">
                        <p class="list_title">Apple</p>
                    </a>
                </li>
                <li class="list_item">
                    <a class="list_link" href="">
                        <img class="list_img" src="<?=$block->getViewFileUrl('CoolBlueModule_Module::images/category/l4-1.png')?>" alt="">
                        <p class="list_title">Asus</p>
                    </a>
                </li>
                <li class="list_item">
                    <a class="list_link" href="">
                        <img class="list_img" src="<?=$block->getViewFileUrl('CoolBlueModule_Module::images/category/l4-2.png')?>" alt="">
                        <p class="list_title">HP</p>
                    </a>
                </li>
                <li class="list_item">
                    <a class="list_link" href="">
                        <img class="list_img" src="<?=$block->getViewFileUrl('CoolBlueModule_Module::images/category/l4-3.png')?>" alt="">
                        <p class="list_title">Lenovo</p>
                    </a>
                </li>
                <li class="list_item">
                    <a class="list_link" href="">
                        <img class="list_img" src="<?=$block->getViewFileUrl('CoolBlueModule_Module::images/category/l4-4.png')?>" alt="">
                        <p class="list_title">Microsoft</p>
                    </a>
                </li>
                <li class="list_item">
                    <a class="list_link" href="">
                        <img class="list_img" src="<?=$block->getViewFileUrl('CoolBlueModule_Module::images/category/l4-6.png')?>" alt="">
                        <p class="list_title">AOC</p>
                    </a>
                </li>
                <li class="list_item">
                    <a class="list_link" href="">
                        <img class="list_img" src="<?=$block->getViewFileUrl('CoolBlueModule_Module::images/category/l4-7.png')?>" alt="">
                        <p class="list_title">LG</p>
                    </a>
                </li>
                <li class="list_item">
                    <a class="list_link" href="">
                        <img class="list_img" src="<?=$block->getViewFileUrl('CoolBlueModule_Module::images/category/l4-8.png')?>" alt="">
                        <p class="list_title">Philips</p>
                    </a>
                </li>
                <li class="list_item">
                    <a class="list_link" href="">
                        <img class="list_img" src="<?=$block->getViewFileUrl('CoolBlueModule_Module::images/category/l4-1.png')?>" alt="">
                        <p class="list_title">Samsung</p>
                    </a>
                </li>
                <li class="list_item">
                    <a class="list_link" href="">
                        <img class="list_img" src="<?=$block->getViewFileUrl('CoolBlueModule_Module::images/category/l4-6.png')?>" alt="">
                        <p class="list_title">Logitech</p>
                    </a>
                </li>
                <li class="list_item">
                    <a class="list_link" href="">
                        <img class="list_img" src="<?=$block->getViewFileUrl('CoolBlueModule_Module::images/category/l4-l.png')?>" alt="">
                        <p class="list_title">Trust</p>
                    </a>
                </li>
            </ul>
        </li>
    </ul>
    <div class="category_section11">
            <ul class="category_section11_lists">
                <li class="category_section11_item">
                    <h3 class="category_section11_item_title">A</h3>
                    <ul class="category_section11_item_list">
                        <li><a class="category_section11_item_link" href="">Acer laptops</a></li>
                        <li><a class="category_section11_item_link" href="">Apple MacBook</a></li>
                        <li><a class="category_section11_item_link" href="">Asus laptops</a></li>
                    </ul>
                </li>
                <li class="category_section11_item">
                    <h3 class="category_section11_item_title">B</h3>
                    <ul class="category_section11_item_list">
                        <li><a class="category_section11_item_link" href="">Back to School laptops</a></li>
                        <li><a class="category_section11_item_link" href="">Best laptops according to our customers</a></li>
                        <li><a class="category_section11_item_link" href="">Black Friday laptop deals</a></li>
                    </ul>
                </li>
                <li class="category_section11_item">
                    <h3 class="category_section11_item_title">C</h3>
                    <ul class="category_section11_item_list">
                        <li><a class="category_section11_item_link" href="">Cheap laptops</a></li>
                        <li><a class="category_section11_item_link" href="">Christmas laptop deals</a></li>
                        <li><a class="category_section11_item_link" href="">Chromebooks</a></li>
                    </ul>
                </li>
                <li class="category_section11_item">
                    <h3 class="category_section11_item_title">D</h3>
                    <ul class="category_section11_item_list">
                        <li><a class="category_section11_item_link" href="">Dell laptops</a></li>
                        <li><a class="category_section11_item_link" href="">Dynabook laptops</a></li>
                        <li><a class="category_section11_item_link" href="">Dynabook laptops</a></li>
                    </ul>
                </li>
            </ul>
        </div>
</div>