<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="menu">
    <div class="menu__column">
        <div>
            <p>You previously viewed:</p>
            <div>
                <p>View your products anywhere</p>
                <p>Log in to see products you previously viewed.</p>
                <button>Log in</button>  
                <p>Don't have an account yet?</p><a href="#">Start here</a>  
            </div>
            <a href="#">View your personal recommendations</a>
        </div>
        <div>
            <p>anything for a smile</p>
            <ul>
                <li>
                    <a href="#">Ordered before 23:59, delivered tomorrow for free</a>
                </li>
                <li>
                   <a href="#">14 stores</a>
                </li>
                <li>
                    <a href="#">Our app</a>
                </li>
                <li>
                    <a href="#">Best webshop 2021</a>
                </li>
            </ul>
        </div>
        <div>
            <img src="" alt="man">
            <div>
                <p>Do you have a question?</p>
                <p>Find your answer quickly and easily on our customer service page.</p>
                <ul>
                    <li>
                        <a href="">Facebook</a>
                    </li>
                    <li>
                        <a href="">YouTube</a>
                    </li>
                    <li>
                        <a href="">Twitter</a>
                    </li>
                    <li>
                        <a href="">14 stores</a>
                    </li>
                </ul>
            </div>
            <div>
                <p>Sign up for our newsletter</p>
                <p>Receive the best promotions and personal advice.</p>
                <form action="">
                    <input type="text"/>
                    <button>Sing up</button>
                </form>
            </div>
        </div>
        <div>
            <ul>
                <li>
                    <ul>
                        <li><a href="">Customer Service</a></li>
                        <li><a href="">Delivery and installation</a></li>
                        <li><a href="">Payment</a></li>
                        <li><a href="">Exchange and return</a></li>
                        <li><a href="">Warranty and repairs</a></li>
                        <li><a href="">Order</a></li>
                        <li><a href="">Stores</a></li>
                        <li><a href="">Status of my order</a></li>
                        <li><a href="">Register a return or repair</a></li>
                        <li><a href="">All orders</a></li>
                        <li><a href="">Log in</a></li>
                        <li><a href="">> To the customer service</a></li>
                    </ul>
                </li>
                <li>
                    <ul>
                        <li><a href="">Business</a></li>
                        <li><a href="">Business order</a></li>
                        <li><a href="">Business gift cards</a></li>
                        <li><a href="">Christmas gifts/a></li>
                        <li><a href="">Company Stores</a></li>
                        <li><a href="">Home Office Store</a></li>
                        <li><a href="">Bring Your Own Device</a></li>
                        <li><a href="">Gift Store</a></li>
                        <li><a href="">Affiliate program</a></li>
                        <li><a href="">> Everything on B2B</a></li>
                    </ul>
                </li>
                <li>
                    <ul>
                        <li><a href="">Our stores</a></li>
                        <li><a href="">Almere</a></li>
                        <li><a href="">Amsterdam</a></li>
                        <li><a href="">Arnhem</a></li>
                        <li><a href="">Den Bosch</a></li>
                        <li><a href="">The Hague</a></li>
                        <li><a href="">Eindhoven</a></li>
                        <li><a href="">Groningen</a></li>
                        <li><a href="">Haarlem</a></li>
                        <li><a href="">Leiden</a></li>
                        <li><a href="">Nijmegen</a></li>
                        <li><a href="">Rotterdam</a></li>
                        <li><a href="">Rotterdam Alexandrium</a></li>
                        <li><a href="">Tilburg</a></li>
                        <li><a href="">Utrecht</a></li>
                        <li><a href="">> Everything on our shops</a></li>
                    </ul>
                </li>
                <li>
                    <ul>
                        <li><a href="">About Coolblue</a></li>
                        <li><a href="">Our assortment</a></li>
                        <li><a href="">Company website</a></li>
                        <li><a href="">Gift cards</a></li>
                        <li><a href="">Careers at Coolblue</a></li>
                        <li><a href="">Development jobs</a></li>
                        <li><a href="">The Coolblue App</a></li>
                        <li><a href="">Coolblue Belgium</a></li>
                        <li><a href="">Coolblue Germany</a></li>
                        <li><a href="">Privacy</a></li>
                        <li><a href="">> Everything on Coolblue</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</div>
