<?php
/**
 * @author      Valia <valiastohnii@gmail.com>
 * @copyright   Copyright (c) 2022 GmbH 
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
*/
?>
<small class="copyright">
    <div class="footer_menu_content footer_menu_content--copyright">
        <ul>
            <li><a href="">Terms & Conditions</a></li>
            <li><a href="">Privacy</a></li>
            <li><a href="">Cookies</a></li>
            <li><a href="">Nederlands (NL)</a></li>
        </ul>
        <span>© 1999 - 2022 - Coolblue B.V.</span>
        <span>Rating by costumers: Kiyoh 9 / 10 - <a href="#">12,285 reviews</a> </span>
    </div>
</small>
