<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="footer_menu">
    <div class="footer_menu_column">
        <hr>
        <div class="footer_menu__section1">
            <div class="footer_menu_content">
                <p class="section1__title">You previously viewed:</p>
                <div class="section1__block">
                    <p class="section1__block__title">View your products anywhere</p>
                    <p class="section1__text">Log in to see products you previously viewed.</p>
                    <button type="button" class="section1__button">Log in</button>  
                    <p class="section1__text">Don't have an account yet?</p><a href="#" class="section1__link">Start here</a>  
                </div>
                <a class="section1__link" href="#">View your personal recommendations</a>
            </div>
        </div>
        <hr>
        <div class="footer_menu__section2">
            <div class="footer_menu_content footer_menu_content--section2">
                <p class="section2__title">anything for a smile</p>
                <ul class="section2__list">
                    <li class="section2__item">
                        <a href="#" class="section2__link">Ordered before <span class="section2__orange">23:59</span>, delivered tomorrow <span class="section2__orange">for free</span></a>
                    </li>
                    <li class="section2__item">
                    <a href="#" class="section2__link">14 stores</a>
                    </li>
                    <li class="section2__item">
                        <a href="#" class="section2__link">Our app</a>
                    </li>
                    <li class="section2__item">
                        <a href="#" class="section2__link"> <span class="section2__orange">Best</span> webshop 2021</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="footer_menu__section3">
            <div class="footer_menu_content footer_menu_content--section3">
                <img src="" alt="man" class="section3__img">
                <div class="section3__block">
                    <p class="section3__title">Do you have a question?</p>
                    <p class="section3__text">Find your answer quickly and easily on our customer service page.</p>
                    <ul class="section3__list">
                        <li class="section3__item">
                            <a href="" class="section3__link">Facebook</a>
                        </li>
                        <li class="section3__item">
                            <a href="" class="section3__link">YouTube</a>
                        </li>
                        <li class="section3__item">
                            <a href="" class="section3__link">Twitter</a>
                        </li>
                        <li class="section3__item">
                            <a href="" class="section3__link">14 stores</a>
                        </li>
                    </ul>
                </div>
                <div class="section3__block">
                    <p class="section3__title">Sign up for our newsletter</p>
                    <p class="section3__text">Receive the best promotions and personal advice.</p>
                    <form action="submit" class="section3__form">
                        <label for="section3__input" class="section3__form form__label">Email address</label>
                        <input name="section3__input" type="email" class="section3__form form__input"/>
                        <button class="section3__form form__button">Sing up</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="footer_menu__section4">
            <div class="footer_menu_content">
                <ul class="section4__list">
                    <li class="section4__item">
                        <ul class="section4__item__list">
                            <li class="section4__link"><a href="">Customer Service</a></li>
                            <li><a href="">Delivery and installation</a></li>
                            <li><a href="">Payment</a></li>
                            <li><a href="">Exchange and return</a></li>
                            <li><a href="">Warranty and repairs</a></li>
                            <li><a href="">Order</a></li>
                            <li><a href="">Stores</a></li>
                            <li><a href="">Status of my order</a></li>
                            <li><a href="">Register a return or repair</a></li>
                            <li><a href="">All orders</a></li>
                            <li><a href="">Log in</a></li>
                            <li class="section4__link__last"><a href="">> To the customer service</a></li>
                        </ul>
                    </li>
                    <li class="section4__item">
                        <ul class="section4__item__list">
                            <li class="section4__link"><a href="">Business</a></li>
                            <li><a href="">Business order</a></li>
                            <li><a href="">Business gift cards</a></li>
                            <li><a href="">Christmas gifts/a></li>
                            <li><a href="">Company Stores</a></li>
                            <li><a href="">Home Office Store</a></li>
                            <li><a href="">Bring Your Own Device</a></li>
                            <li><a href="">Gift Store</a></li>
                            <li><a href="">Affiliate program</a></li>
                            <li class="section4__link__last"><a href="">> Everything on B2B</a></li>
                        </ul>
                    </li>
                    <li class="section4__item">
                        <ul class="section4__item__list">
                            <li class="section4__link"><a href="">Our stores</a></li>
                            <li><a href="">Almere</a></li>
                            <li><a href="">Amsterdam</a></li>
                            <li><a href="">Arnhem</a></li>
                            <li><a href="">Den Bosch</a></li>
                            <li><a href="">The Hague</a></li>
                            <li><a href="">Eindhoven</a></li>
                            <li><a href="">Groningen</a></li>
                            <li><a href="">Haarlem</a></li>
                            <li><a href="">Leiden</a></li>
                            <li><a href="">Nijmegen</a></li>
                            <li><a href="">Rotterdam</a></li>
                            <li><a href="">Rotterdam Alexandrium</a></li>
                            <li><a href="">Tilburg</a></li>
                            <li><a href="">Utrecht</a></li>
                            <li class="section4__link__last"><a href="">> Everything on our shops</a></li>
                        </ul>
                    </li>
                    <li class="section4__item">
                        <ul class="section4__item__list">
                            <li class="section4__link"><a href="">About Coolblue</a></li>
                            <li><a href="">Our assortment</a></li>
                            <li><a href="">Company website</a></li>
                            <li><a href="">Gift cards</a></li>
                            <li><a href="">Careers at Coolblue</a></li>
                            <li><a href="">Development jobs</a></li>
                            <li><a href="">The Coolblue App</a></li>
                            <li><a href="">Coolblue Belgium</a></li>
                            <li><a href="">Coolblue Germany</a></li>
                            <li><a href="">Privacy</a></li>
                            <li class="section4__link__last"><a href="">> Everything on Coolblue</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
